# Demo values: project default, all applications enabled
# Used by bootstrap.yaml for the App of Apps
---
server: https://kubernetes.default.svc
clusterName: in-cluster
projectName: demo

guestbook:
  enabled: true
  targetRevision: main
  namespace: guestbook

helmGuestbook:
  enabled: true
  valueFile: values.yaml
  targetRevision: main
  namespace: guestbook

helmHooks:
  enabled: false
  targetRevision: main
  namespace: helm-hooks

syncwaves:
  enabled: false
  targetRevision: main
  namespace: syncwaves
